server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 281265839632-d7i4f968kpeos768dtl5n9fqlf1rmkqd.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    org:
      springframework:
        security: TRACE


springdoc:
  api-docs:
    enabled: true